FROM mysql:26.7.0-oraclelinux9@sha256:66aec17cd21a956029b83f083b813073859e8355dc1a00e55df6ba02f0e32345

# AQMS tidak memakai MySQL Shell. util-linux menyediakan setpriv sehingga
# entrypoint tetap menurunkan hak akses ke user mysql tanpa binary Go gosu.
RUN microdnf install -y util-linux \
    && microdnf remove -y mysql-shell \
    && sed -i 's/exec gosu mysql "$BASH_SOURCE" "$@"/exec setpriv --reuid=mysql --regid=mysql --init-groups "$BASH_SOURCE" "$@"/' /usr/local/bin/docker-entrypoint.sh \
    && rm -f /usr/local/bin/gosu \
    && microdnf clean all \
    && rm -rf /var/cache/dnf
